- project:
    name: openstack/ironic
    check:
      jobs:
       - HPE-Gen9-ironic-container-standalone-wholedisk-uefi-ilo-virtual-media-direct-python3
       - HPE-Gen9-ironic-container-standalone-wholedisk-uefi-ilo-ipxe-direct-python3
       - HPE-Gen10-ironic-container-standalone-wholedisk-ilo-uefi-https-direct-python3
