- hosts: all
  name: HPE ilo-ipxe job
  tasks:

    - block:
        - name: Generate MoltenIron Id for node
          command: uuidgen
          register: uuid

        - name: Clone gate jobs
          shell: cd /home/citest; git clone https://github.com/hpproliant/NEW-HPE-CI-CONFIG.git

        - name: Kolla bootstrapping and Kolla deploy
          shell: /home/citest/NEW-HPE-CI-JOBS/kolla-deploy.sh

        - name: Injecting new patch to ironic container and do reconfigure
          shell: /home/citest/NEW-HPE-CI-JOBS/ironic-patch-injection.sh {{zuul.ref}}

        - name: Prepare gate
          shell: /home/citest/NEW-HPE-CI-JOBS/prepare-gate.sh

        - name: Allocating test node
          command: /home/citest/NEW-HPE-CI-JOBS/molteniron/allocate_molten.py {{ uuid.stdout }} Gen9 loose

        - name: Running ilo-ipxe gate
          shell: /home/citest/NEW-HPE-CI-JOBS/ilo-ipxe/gate.sh  2>&1 | tee /home/citest/gate_logs/gate.logs
      always:
        - name: Deallocating test node
          shell: /home/citest/NEW-HPE-CI-JOBS/molteniron/release_molten.py {{ uuid.stdout }}
