- hosts: all
  name: HPE Proliant ilo5 uefi https job
  tasks:

    - name: Create workspace directory to run ilo5-uefi-https
    - block:
        - name: Cloning ilo5-uefi-https gate
          shell: cd /home/citest; git clone https://github.com/hpproliant/NEW-HPE-CI-JOBS.git

        - name: Waiting for host to get CI ready (Kolla bootstrapping)
          shell: while [ $CI_READY != "true" ];do sleep 1; done

        - name: Injecting new patch to ironic container and setting ironic.conf
          shell: /home/citest/NEW-HPE-CI-JOBS/ironic_patch_injection.sh {{zuul.ref}}

        - name: Preparing the gate
          shell: /home/citest/NEW-HPE-CI-JOBS/prepare-gate.sh

        - name: Generate MoltenIron Id for node
          command: uuidgen
          register: uuid

        - name: Allocating test node
          command: /home/citest/NEW-HPE-CI-JOBS/molteniron/allocate_molten.py {{ uuid.stdout }} Ironic_Gen10

        - name: Running ilo5-uefi-https gate
          shell: /home/citest/NEW-HPE-CI-JOBS/ilo5-uefi-https/gate.sh

      always:
        - name: Deallocating test node
          shell: /home/citest/NEW-HPE-CI-JOBS/molteniron/release_molten.py {{ uuid.stdout }}