- hosts: all
  name: HPE Proliant ilo5 uefi https job
  tasks:

    - name: Create workspace directory to run ilo5-uefi-https
    - block:
        - name: Clone gate jobs
          shell: cd /home/citest; git clone https://github.com/hpproliant/NEW-HPE-CI-JOBS.git

        - name: Kolla bootstrapping and Kolla deploy
          shell: /home/citest/NEW-HPE-CI-JOBS/kolla-deploy.sh

        - name: Injecting new patch to ironic container and do reconfigure
          shell: /home/citest/NEW-HPE-CI-JOBS/ironic-patch-injection.sh {{zuul.ref}}

        - name: Prepare gate
          shell: /home/citest/NEW-HPE-CI-JOBS/prepare-gate.sh

        - name: Generate MoltenIron Id for node
          command: uuidgen
          register: uuid

        - name: Allocating test node
          command: /home/citest/NEW-HPE-CI-JOBS/molteniron/allocate_molten.py {{ uuid.stdout }} Gen10 strict

        - name: Running ilo5-uefi-https gate
          shell: /home/citest/NEW-HPE-CI-JOBS/ilo5-uefi-https/gate.sh 2>&1 | tee /home/citest/gate_logs/gate.logs

      always:
        - name: Remove TLS cert
          shell: /home/citest/NEW-HPE-CI-JOBS/ilo5-uefi-https/files/remove_cert

        - name: Deallocating test node
          shell: /home/citest/NEW-HPE-CI-JOBS/molteniron/release_molten.py {{ uuid.stdout }}
