- hosts: all
  name: HPE Proliant ilo5 uefi https job
  tasks:
    - block:
        - name: Generate MoltenIron Id for node
          command: uuidgen
          register: uuid

        - name: Allocating test node
          command: /home/citest/NEW-HPE-CI-JOBS/molteniron/allocate_molten.py {{ uuid.stdout }} Gen10 strict

        - name: Clone gate jobs
          shell: cd /home/citest; git clone https://github.com/hpproliant/NEW-HPE-CI-JOBS.git

        - name: Kolla bootstrapping and Kolla deploy
          shell: /home/citest/NEW-HPE-CI-JOBS/kolla-deploy.sh

        - name: Running ilo5-uefi-https gate
          shell: /home/citest/NEW-HPE-CI-JOBS/ilo5-uefi-https/gate.sh {{zuul.ref}} 2>&1 | tee /home/citest/gate_logs/gate.logs

        - name: Deallocating test node
          shell: /home/citest/NEW-HPE-CI-JOBS/molteniron/release_molten.py {{ uuid.stdout }}

        - name: Remove cert
          shell: /home/citest/NEW-HPE-CI-JOBS/ilo5-uefi-https/files/remove_cert
      rescue:
        - name: Deallocating test node
          shell: /home/citest/NEW-HPE-CI-JOBS/molteniron/release_molten.py {{ uuid.stdout }}
        
        - name: Remove cert
          shell: /home/citest/NEW-HPE-CI-JOBS/ilo5-uefi-https/files/remove_cert

        - name: Job failed
          fail:
            msg: "HPE ilo5-uefi-https job failed."
