- hosts: all
  name: HPE Proliant redfish-virtual-media job
  tasks:

    - name: Create workspace directory to run redfish-virtual-media
    - block:
        - name: Waiting for host to get CI ready (Kolla bootstrapping)
          shell: while [[ ! -f "/home/citest/ci_ready" && ! -f "/home/citest/ci_failed" ]];do sleep 1; done
        
        - name: Checking for success status
          shell: if [ -f "/home/citest/ci_failed" ];then exit 1; fi

        - name: name: Injecting new patch to ironic container and setting ironic.conf
          shell: /home/citest/NEW-HPE-CI-JOBS/ironic_patch_injection.sh {{zuul.ref}}

        - name: Generate MoltenIron Id for node
          command: uuidgen
          register: uuid

        - name: Allocating test node
          command: /home/citest/NEW-HPE-CI-JOBS/molteniron/allocate_molten.py {{ uuid.stdout }} Gen10 strict

        - name: Running redfish-virtual-media
          shell: /home/citest/NEW-HPE-CI-JOBS/redfish-virtual-media/gate.sh 2>&1 | tee /home/citest/gate_logs/gate.logs

      always:
        - name: Deallocating test node
          shell: /home/citest/NEW-HPE-CI-JOBS/molteniron/release_molten.py {{ uuid.stdout }}
