- hosts: all
  name: HPE ilo-ipxe job
  tasks:

    - name: Generate MoltenIron Id for node
      command: uuidgen
      register: uuid

    - name: Clone gate jobs
      shell: cd /home/citest; git clone https://github.com/hpproliant/NEW-HPE-CI-JOBS.git

    - name: Kolla bootstrapping and Kolla deploy
      shell: /home/citest/NEW-HPE-CI-JOBS/kolla-deploy.sh

    - name: Allocating test node
      command: /home/citest/NEW-HPE-CI-JOBS/molteniron/allocate_molten.py {{ uuid.stdout }} Gen9 strict

    - name: Running ilo-ipxe gate
      shell: /home/citest/NEW-HPE-CI-JOBS/ilo-ipxe/gate.sh {{zuul.ref}} {{ uuid.stdout }} 2>&1 | tee /home/citest/gate_logs/gate.log