- hosts: all
  name: HPE Proliant redfish-virtual-media job
  tasks:

    - name: Create workspace directory to run redfish-virtual-media
    - block:
        - name: Kolla bootstrapping and Kolla deploy
          shell: /home/citest/NEW-HPE-CI-JOBS/kolla-deploy.sh

        - name: Injecting new patch to ironic container and do reconfigure
          shell: /home/citest/NEW-HPE-CI-JOBS/ironic-patch-injection.sh {{zuul.ref}}

        - name: Prepare gate
          shell: /home/citest/NEW-HPE-CI-JOBS/prepare-gate.sh

        - name: Generate MoltenIron Id for node
          command: uuidgen
          register: uuid

        - name: Allocating test node
          command: /home/citest/NEW-HPE-CI-JOBS/molteniron/allocate_molten.py {{ uuid.stdout }} Gen10 strict

        - name: Running redfish-virtual-media
          shell: /home/citest/NEW-HPE-CI-JOBS/redfish-virtual-media/gate.sh 2>&1 | tee /home/citest/gate_logs/gate.logs

      always:
        - name: Deallocating test node
          shell: /home/citest/NEW-HPE-CI-JOBS/molteniron/release_molten.py {{ uuid.stdout }}
