- hosts: all
  name: HPE Proliant redfish-ipxe job
  tasks:

    - name: Create workspace directory to run redfish-ipxe
    - block:
        - name: Waiting for host to get CI ready (Kolla bootstrapping)
          shell: while [ ! -f "/home/citest/ci_ready" ];do sleep 1; done

        - name: name: Injecting new patch to ironic container and setting ironic.conf
          shell: /home/citest/NEW-HPE-CI-JOBS/ironic_patch_injection.sh {{zuul.ref}}

        - name: Generate MoltenIron Id for node
          command: uuidgen
          register: uuid

        - name: Allocating test node
          command: /home/citest/NEW-HPE-CI-JOBS/molteniron/allocate_molten.py {{ uuid.stdout }} Gen10 strict

        - name: Running redfish-ipxe
          shell: /home/citest/NEW-HPE-CI-JOBS/redfish-ipxe/gate.sh 2>&1 | tee /home/citest/gate_logs/gate.logs

      always:
        - name: Deallocating test node
          shell: /home/citest/NEW-HPE-CI-JOBS/molteniron/release_molten.py {{ uuid.stdout }}
