- hosts: all
  tasks:

    - name: Set log path for a change
      when: zuul.change is defined
      set_fact:
        log_path: "{{ zuul.change[-2:] }}/{{ zuul.change }}/{{ zuul.patchset }}/{{ zuul.pipeline }}/{{ zuul.job }}/{{ zuul.build[:7] }}"

    - name: Set log path for a ref update
      when: zuul.newrev is defined
      set_fact:
        log_path: "{{ zuul.newrev[-2:] }}/{{ zuul.newrev }}/{{ zuul.pipeline }}/{{ zuul.job }}/{{ zuul.build[:7] }}"

    - name: Set log path for a periodic job
      when: zuul.change is not defined and zuul.newrev is not defined
      set_fact:
        log_path: "{{ zuul.pipeline }}/{{ zuul.job }}/{{ zuul.build[:7] }}"

    - name: Preparing file for logs
      tempfile:
        state: file
      register: tmpe
      no_log: true

    - block:
        - name: Preparing logs
          copy:
            content: |
              # Copy ansible logs
              mkdir -p /home/citest/gate_logs/zuul_executor
              ssh -i /home/citest/zuul_id_rsa -o StrictHostKeyChecking=no zuul@169.16.1.40 "sudo chown -R zuul.zuul {{ zuul.executor.log_root }}"
              ssh -i /home/citest/zuul_id_rsa -o StrictHostKeyChecking=no zuul@169.16.1.40 "sudo chmod -R 0777 /tmp; sudo chown -R zuul.zuul /tmp"
              scp -i /home/citest/zuul_id_rsa -o StrictHostKeyChecking=no -r zuul@169.16.1.40:{{ zuul.executor.log_root }} /home/citest/gate_logs/zuul_executor/
              
              # Copy kolla services logs
              mkdir -p /home/citest/gate_logs/kolla_services
              sudo cp -R /var/log/kolla/ /home/citest/gate_logs/kolla_services/
              sudo chown -R citest.citest /home/citest/gate_logs
              rm -f /home/citest/gate_logs/kolla_services/kolla/ironic/*.gz
                         
              # Copy misc logs
              sudo cp /home/citest/ci_init.log /home/citest/gate_logs/

              # Copy configurations
              mkdir -p /home/citest/gate_logs/etc
              sudo chown -R citest.citest /etc/kolla/*
              sudo rm -rf /etc/kolla/config
              sudo rm -rf /etc/kolla/ironic-http/*.ipxe /etc/kolla/ironic-http/*.efiboot /etc/kolla/ironic-http/*.initramfs /etc/kolla/ironic-http/*.kernel /etc/kolla/ironic-http/*.qcow2
              sudo cp -R /etc/kolla/ /home/citest/gate_logs/etc/
              sudo chown -R citest.citest /home/citest/gate_logs
              cp /home/citest/gate-test/tempest/etc/tempest.conf /home/citest/gate_logs/etc/

              # Create cleaning info
              timestamp=$(date +%s)
              cat <<EOF >/home/citest/gate_logs/clean_info.json
              {
                "job_id": "{{ log_path }}",
                "job_timestamp": $timestamp
              }
              EOF

              # Copy logs to log-server
              tar -cvf /home/citest/{{ zuul.change }}_{{ zuul.patchset }}_{{ zuul.job }}.tar -C /home/citest gate_logs/
              scp -i /home/citest/logserver_id_rsa -o StrictHostKeyChecking=no /home/citest/{{ zuul.change }}_{{ zuul.patchset }}_{{ zuul.job }}.tar logserver@169.16.1.30:~/INCOMING_LOGS/

              # Push logs to GIT
              curl -X POST -d '{"paste_path": "{{ log_path }}", "tar_name": "{{ zuul.change }}_{{ zuul.patchset }}_{{ zuul.job }}.tar"}' -H 'Content-Type: application/json' http://169.16.1.30/logs/upload

            dest: "{{ tmpe.path }}"
            mode: 0777
          no_log: true
          become: true

        - name: Posting logs to logserver
          shell: bash {{ tmpe.path }}
      always:
        - name: Post logs to gerrit
          delegate_to: localhost
          zuul_return:
            data:
             zuul:
                log_url: "https://hpproliant.github.io/hpeproliant.github.io/logs/{{ log_path }}/{{ zuul.build[:7] }}.html"
